version: '3.7'

services:
  vue-app:
    image: jochre3-search-client:0.0.1
    restart: always
    ports:
      - '5173:8080'
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
