version: '3.7'

services:
  jochre3-search-client:
    container_name: jochre3-search-client
    image: registry.gitlab.com/jochre/jochre3-search-client:0.1.5
    restart: on-failure
    ports:
      - '5173:80'
    volumes:
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./frontend-config.json:/usr/share/nginx/html/conf/config.json
      - ./yiddishbookcenter-ocr.jpg:/usr/share/nginx/html/images/yiddishbookcenter-ocr.jpg
      - ./privacy.html:/usr/share/nginx/html/privacy.html
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
