version: '3.7'

services:
  jochre3-search-client:
    container_name: jochre3-search-client
    image: registry.gitlab.com/jochre/jochre3-search-client:0.1.0
    restart: on-failure
    ports:
      - '5173:8080'
    volumes:
      - ./favicon.ico:/app/dist/favicon.ico
      - ./frontend-config.json:/app/dist/conf/config.json
      - ./yiddishbookcenter-ocr.jpg:/app/dist/images/yiddishbookcenter-ocr.jpg
      - ./privacy.html:/app/dist/privacy.html
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
